# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be629c9f2e8c5cfddd5bbbedc60f649b727cc0516aff1024fc9fe1da751a62ed8d9ae1c8b98b018882d7de331271972863c328aadf8373ec98fd3beaf9c44c33

test:
  secret_key_base: 156c8841a358b4ed3a56fb45420493e523fda528b1bd6ae48011585c69c08579390360dc1a2b9ef4c3defc276f0d6c35ba6837c292c6f695bfbc8cd395997044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
